# Site settings
description: A blog about lorem ipsum dolor sit amet
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://2joephillips.github.io" # the base hostname & protocol for your site 

# User settings
username: Joseph E Phillips
user_description: Joseph E Phillips
user_title: Father, Geek, Programmer
email: joseph@josephephillips.com
twitter_username: 2joephillips
github_username:  2joephillips
gplus_username:  lorem_ipsum
disqus_username: 2joephillipsgithubio

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Blog
    url: /blog
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
