# Site settings
title: Joseph E Phillips
description: "Father // Marathoner // Programmer"
email: joseph@josephephillips.com


#about section settings
blurb: <strong>Joseph solves problems </strong> by creating web presence, developing online stores,
            or consulting all types of companies and non-porfit organizations.
            In his spare time he is an avid Netflixer and constant learner of
            web technologies.

#Menu Item List
menu:
- {name: Home, url: ''}
- {name: About Me, url: '#about-me'}
- {name: Projects, url: '#projects'}
- {name: Clients, url: '#clients'}
- {name: Blog, url: 'blog'}
- {name: Contact, url: '#contact'}


#Skill List
skills:
- {name: Communication, value: '8'}
- {name: Learning, value: '9'}
- {name: Organization, value: '6'}
- {name: Planning, value: '7'}
- {name: Programming, value: '9'}
- {name: Project Mangement, value: '8'}

#Projects List
projects:
- {name: The Soccer Tutor, folder: 'proj-1'}
- {name: Fresno Counseling, folder: 'proj-2'}
- {name: HillWood Home Team, folder: 'proj-3'}
- {name: Bark And Boogie Ball, folder: 'proj-4'}


#-------------------------------
# Clients Section

clients:

- {avatar: 'face-zachary.jpg',
  name: 'Zachary Bates',
  title: 'Analyst, State Farm',
  quote: '<p><strong>Know him to be a professional, poised, and dedicated individual. </strong>He is a creative and quick thinker. Most recently, we have worked together during a time of high volume, evolving processes and workflows, and shifting focus and priorities. </p>',
  logo: 'logo2.png'}
- {avatar: 'face-robert.jpg',
  name: 'Robert Kracke',
  title: 'Special Projects Lead, Southern Company',
  quote: '<p><strong>He always ended up on the technical leadership side of the spectrum.</strong> He has a desire for knowledge and seeks to be a leader. He has an excellent demeanor and is very easy...</p>',
  logo: 'logo3.png'}
#- {avatar: 'face-casey.jpg',
#  name: 'Casey Wood',
#  title: 'Broker, HillWood Realty',
#  quote: '<p><strong>Back in old country</strong> only nerds who is playing on computers. Now all bros is wanting to make codes and junk. I lost foot in war. You dont see girls asking me about homework.</p>',
#  logo: 'logo4.png'}
- {avatar: 'face-andy.jpg',
  name: 'Andy Darnell',
  title: 'Owner, WingSpan Marketing',
  quote: '<p><strong>He as a great ability to identify technical challenges</strong> which may arise during the development process, but he also has the ability to problem solve when challanges arise.</p>',
  logo: 'logo1.png'}


#Social List using FontAwesome
social:
- {icon: 'fa-facebook', link: 'https://www.facebook.com/2josephillips'}
- {icon: 'fa-instagram', link: 'https://www.instagram.com/2joephillips/'}
- {icon: 'fa-github', link: 'https://github.com/2joephillips'}
- {icon: 'fa-twitter', link: 'https://twitter.com/2joephillips'}
- {icon: 'fa-pinterest-p', link: 'https://www.pinterest.com/2joephillips/'}
#- {icon: 'fa-envelope-o', link: 'mailto:joseph@josephephillips.com'}
